### PR TITLE
Loosen version requirements for all dependencies

### LINKED ISSUE #104: mytoyota 0.7.4 dependency requierement error
**Describe the bug**
I'm trying to use MyToyota Connected Services and it's requiere mytoyota 0.7.4, so I've tryed to install it:

I cannot install the package (either via pip and webinterface), get 

```
mytoyota 0.7.4 requires httpx<0.19.0,>=0.18.1, but you have httpx 0.19.0 which is incompatible.
```

**To Reproduce**
upgrade python3.8 .11 (Debian version)

**Expected behavior**
working with latest httpx version (0.19.0)

**Screenshots**
N/A

**Additional context**

### PR DESCRIPTION
**Pull request by DurgNomis-drol**
Closes #104 

There is no need for them to be so strict, I wasn't that familier with how to set this up when I did it. The only one that is important is `langcodes`, but i believe it is still in the correct range.

### CODE REVIEW

**Review by joro75 — CHANGES_REQUESTED** [review]
I'm afraid that this change is not going to fix the issue #104. In that issue the poster wrote that he has httpx 0.19 on his Debian installation.
If I understand the [poetry dependency specification](https://python-poetry.org/docs/dependency-specification/) correctly, then `httpx = "^0.18"` only allows the version range; 0.18.0.0 up to and including 0.18.999.999. 
The httpx of 0.19 on the Debian installation of the poster will thus still not be supported.

A better version requirement is probably: `httpx = ">=0.18.1"`.

**Comment by DurgNomis-drol** [comment]
I read it as the opposite. If you look below, setting it to `0.18` allows all version from `0.18.0` to `0.999999.999999`. The one you suggests is how it is now, it only allows `0.18.1` to `0.18.99999999999` to be installed. 

Udklip

**Comment by joro75** [comment]
On the [poetry dependency specification](https://python-poetry.org/docs/dependency-specification/) page it is written: `Caret requirements allow SemVer compatible updates to a specified version. An update is allowed if the new version number does not modify the left-most non-zero digit in the major, minor, patch grouping`.
With `^0.18` the left-most non-zero digit (18) may not be modified by the update. So updating to 0.19 is not allowed. 

The >= that I suggested is in my opinion working across all the major, minor, patch grouping. Thus 2.3.4 >= 1.4.5 and 1.20.3 >= 0.26.4 and thus also 0.19.0 >= 0.18.1.

**Comment by DurgNomis-drol** [comment]
Right now it is `>=0.18.1`and that is causing him issues, so clearly that does not work.

The left most none zero digit is still 18 when setting it to `0.18.1` instead of what I suggest `0.18`. I am no expert at all at this and will look closer into this in coming weekend 😊

**Comment by joro75** [comment]
One additional remark: At this moment it is '^0.18.1' which is something else than '>=0.18.1'

**Comment by DurgNomis-drol** [comment]
Right, the last comment you posted, made me understand what i was missing. Thanks reviewing, learned something new today :)

Please review my latest changes

**Review by joro75 — APPROVED** [review]

**Comment by DurgNomis-drol** [comment]
Thanks!! :heart:

**Comment by joro75** [comment]
I can confirm that the dependencies for poetry are now working correctly.
During an update to mytoyota 0.7.5, by using pip, I got:
```
Requirement already satisfied: httpx>=0.18.1 in /usr/local/lib/python.....
Requirement already satisfied: arrow<2.0,>=1.1 in /usr/local/lib/python.....
Requirement already satisfied: langcodes<4.0,>=3.1 in /usr/local/lib/python.....
```
The dependency on httpx is now thus >= 0.18.1, and also httpx 0.19 is now allowed to fulfill the requirement.

**Comment by DurgNomis-drol** [comment]
Awesome, Home Assistant just pushed there's to `0.21` a couple of days ago, so really glad we got this fixed. 😄

**Comment by joro75** [comment]
Ok. I updated my installation also. It is running on httpx version 0.21.1 now, and seems to be running ok.

**Pull request merged**
