### PR TITLE
Enhancement: Add hybrid_score to trip model

### PR DESCRIPTION
**Pull request by rhuijben**
Make the hybrid scrore available on the trip model.

(Tested with Toyota Corolla TS 2020)

### CODE REVIEW

**Comment by CM000n** [comment]
Hello @rhuijben , thank you very much for your contribution!
Could you run pre-commit for the linting? Otherwise the PR looks good to me so far.

**Comment by rhuijben** [comment]
I'll try. Not sure if the name should be score (api) or hybrid score (marketing)

Wouldn't be surprised if they use a different score for full hybrid

**Comment by rhuijben** [comment]
poetry doesn't work on my FreeBSD machine where I use the library. But I ran it on a linux machine and fixed some whitespace. Followed the Toyota model and called it just `score` now.

**Comment by CM000n** [comment]
Thank you very much. ❤️ Looks good to me :)
Sorry for the late response, but I am currently very busy in my private life.

**Review by CM000n — APPROVED** [review]

**Pull request merged**
