### PR TITLE
Fix "setup Connected Services Error" due to latest API Changes

### PR DESCRIPTION
**Pull request by CM000n**
Possible fix for https://github.com/DurgNomis-drol/ha_toyota/issues/164

It seems that the previous API endpoint will continue to be used for the basic car information even after the switch to the new MyToyota app (until now).
However, the structure of the returned data has apparently changed, which is why the check whether Connected Services are activated fails.
In the case of my Toyota Corolla, the information about the Connected Service now looks like this:

```python
{'alias': 'Corolla',
 'claimedBy': 'CUSTOMER',
 'connected': False,
 'connectedService': {'devices': [{'brand': 'TOYOTA',
                                   'countryOfUsage': 'DE',
                                   'customerId': 'my-secret-customer-id',
                                   'deviceId': 'my-secret-device-id',
                                   'linkedWithCustomer': True,
                                   'privacy': False,
                                   'provider': 'DCM19',
                                   'state': 'ACTIVE',
                                   'subState': 'ACTIVE',
                                   'vin': 'my-secret-vin'}],
                      'registrationPreReqs': [],
                      'registrationTerms': [],
                      'status': 'DISABLED',
                      'wifiBoxData': None},
 'entitledBy': 'CUSTOMER',
 'entitledOn': '2023-10-31T16:56:02.541Z',
 'fud': False,
 'hasAutomaticMMRegistration': False,
 'id': my-secret-id,
 'isEntitled': True,
 'isNC': False,
 'isOneAppMigrated': True,
 'isRentalVehicle': False,
 'owner': True,
 'ownerFlag': True,
 'source': 'NMSC',
 'startDate': '2023-10-31T16:56:02.541Z',
 'vehicleAddedOn': '2020-11-19T17:36:19.469Z',
 'vin': 'my-secret-vin'}
```

This change requires that the query for activated connected services be adjusted to determine whether there is a connected service device with an activated status whose Vin matches the vehicle's Vin.

**To be discussed**: Perhaps checking for an activated device with a suitable Vin is not sufficient? Information from other users would be desirable. Maybe it also makes sense to skip checking whether connected services are activated entirely?

### CODE REVIEW

**Review by DurgNomis-drol — DISMISSED** [review]
LGTM! Can you confirm this works? 🚀

**Comment by CM000n** [comment]
> LGTM! Can you confirm this works? 🚀

yes, that works (in my case). But as already written, I can't really validate whether this is a sufficient check, whether the connected services are set up, or whether it doesn't check something completely different.

**Comment by CM000n** [comment]
Hy @DurgNomis-drol I would also like to suggest cancelling python3.7 support, since pylint < 3.0.0 is probably incompatible with python >= 3.11, but pylint >= 3.0.0 no longer supports python < 3.8 versions.

**Comment by DurgNomis-drol** [comment]
@CM000n That would be great, but @joro75 dependes on it for his integration for Domoticz. I have asked him if it is possible for him to upgrade his integration to support the newest python version

**Comment by joro75** [comment]
@CM000n and @DurgNomis-drol  I also fixed some other Pull requests today, and I observed the same. Python < 3.8 is not supported anymore by a lot of dependencies that we are using. Please see PR #237, where I also suggested to require Python >= 3.8.1.

For me it is OK to go to Python >= 3.8

**Comment by joro75** [comment]
Regarding the actual change on the improved check of the connected services: I will try to check it tomorrow on my Toyota.

**Comment by joro75** [comment]
I'm still using the 'old' MyT application, as I have not been converted yet to the 'MyToyota' app. 
I have checked the modifications, and can confirm that they are still working for my situation. I did add an additional check to prevent TypeErrors when the vin of the car and the vin of the devices are not matching.

**Review by joro75 — APPROVED** [review]

**Review by joro75 — APPROVED** [review]

**Pull request merged**
