### PR TITLE
Include year and week as integers in statistical bucket data

### PR DESCRIPTION
**Pull request by joro75**
Fixes: #139: The 'year' information in the 'bucket' of the statistics is sometimes a string and sometimes an integer

The year and week are now always included as integers in the 'bucket' dictionary that is part of the driving statistics.

### CODE REVIEW

**Review by DurgNomis-drol — DISMISSED** [review]
Awesome! What about the tests?

**Comment by joro75** [comment]
Yes, the unittests should indeed be modified too. 
But to be able to do that, I first have to merge and finalize the PR #138, but that is facing some other problems. 
I can probably fix that tomorrow.

**Comment by joro75** [comment]
I have merged and triggered the action again.
But it still requires a review again.... (sorry for that).

**Comment by DurgNomis-drol** [comment]
No problem!

**Review by DurgNomis-drol — APPROVED** [review]

**Pull request merged**
